"""Build the tuning set, kept disjoint from every test set (X, XL, NDS, NeuOpt).

  data/tuning/xml100/  one XML100 instance per attribute combination (depot
                       position, customer positioning, demand distribution,
                       route size = the 4-digit code in the name), skipping
                       instances whose reference solution is invalid.
                       Rounded distances, BKS available.
  data/tuning/gen{N}/  uniform instances, Nazari/Kool law (U[0,1]^2 coordinates,
                       integer demands U{1..9}), seeds disjoint from the NDS and
                       NeuOpt test sets. Real-valued distances, no BKS.
  data/tuning/xlike/   instances from the official X/XML generator (Uchoa et al.
                       2017; Queiroga et al. 2022), n in 200..1000, attributes
                       drawn at random; route-size levels 1-5 only, as in X
                       (level 6, "ultra long", was introduced for XML100).
                       Rounded distances, no BKS.

    uv run python -m bench.make_tuning_set
"""

import random
import subprocess
import sys

import numpy as np

from bench.common import DATA, ROOT, write_vrp

SEED = 20260915
# n -> (instances, capacity); capacities follow cw.c for n <= 500 and NDS beyond
GENERATED = {100: (40, 50), 200: (30, 70), 500: (20, 100), 1000: (15, 200), 2000: (10, 300)}
XLIKE_N, XLIKE_PER_N = (200, 400, 600, 800, 1000), 12
GENERATOR = ROOT / "external_code" / "xml_generator" / "generator.py"


def xml100_subset() -> None:
    src = DATA / "cvrplib" / "XML100"
    invalid = set((DATA / "cvrplib" / "XML100_invalid_ref.txt").read_text().split())
    rng = np.random.default_rng(SEED)
    by_code: dict[str, list] = {}
    for f in sorted(src.glob("*.vrp")):
        if f.stem not in invalid:
            by_code.setdefault(f.stem.split("_")[1], []).append(f)
    out = DATA / "tuning" / "xml100"
    out.mkdir(parents=True, exist_ok=True)
    for files in by_code.values():
        pick = files[rng.integers(len(files))]
        link = out / pick.name
        if not link.exists():
            link.symlink_to(pick.resolve())
    print(f"xml100: {len(by_code)} attribute combinations -> {out}")


def generated() -> None:
    for n, (m, cap) in GENERATED.items():
        rng = np.random.default_rng([SEED, n])
        out = DATA / "tuning" / f"gen{n}"
        out.mkdir(parents=True, exist_ok=True)
        for k in range(m):
            xy = rng.random((n + 1, 2))
            dem = np.concatenate([[0], rng.integers(1, 10, n)])
            write_vrp(out / f"gen{n}_{k:03d}.vrp", f"gen{n}_{k:03d}", xy, dem, cap,
                      comment="uniform customers, demands 1..9, generated by bench/make_tuning_set.py")
        print(f"gen{n}: {m} instances (Q={cap}) -> {out}")


def xlike() -> None:
    out = DATA / "tuning" / "xlike"
    out.mkdir(parents=True, exist_ok=True)
    rng = random.Random(SEED)
    k = 0
    for n in XLIKE_N:
        for _ in range(XLIKE_PER_N):
            k += 1
            depot, cust, dem, rsize = rng.randint(1, 3), rng.randint(1, 3), rng.randint(1, 7), rng.randint(1, 5)
            if not (out / f"XML{n}_{depot}{cust}{dem}{rsize}_{k:02d}.vrp").exists():
                # generator.py argument order: n depotPos custPos demandType avgRouteSize instanceID randSeed
                subprocess.run([sys.executable, str(GENERATOR), str(n), str(depot), str(cust), str(dem),
                                str(rsize), str(k), str(SEED + k)], cwd=out, check=True)
    print(f"xlike: {k} instances -> {out}")


if __name__ == "__main__":
    xml100_subset()
    generated()
    xlike()
