#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate baseline.tex from baseline.csv.

pgfplotstable cannot read quoted CSV fields containing a comma
("NeuOpt-GIRE (D2A=1, T=1k)"), hence generating the .tex beforehand rather
than using a direct \\pgfplotstableread.

Usage:
    python3 make_tex.py [baseline.csv] [baseline.tex]
"""
import csv
import os
import sys

SIZES = (20, 50, 100)
TYPE_STYLE = {                       # order = legend order
    "H":      ("mark=square*,  draw=black,      fill=black!15",  "Classical (H)"),
    "L2S/RL": ("mark=*,        draw=RoyalBlue,  fill=RoyalBlue!30", "Learn-to-search"),
    "L2C/RL": ("mark=triangle*,draw=BrickRed,   fill=BrickRed!30",  "Learn-to-construct"),
}


def esc(s):
    """Escape the LaTeX active characters that occur in our fields."""
    for a, b in (("\\", r"\textbackslash{}"), ("&", r"\&"), ("%", r"\%"),
                 ("_", r"\_"), ("#", r"\#"), ("$", r"\$")):
        s = s.replace(a, b)
    return s


def cell(v):
    return esc(v) if v else "--"


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    src = sys.argv[1] if len(sys.argv) > 1 else os.path.join(here, "baseline.csv")
    dst = sys.argv[2] if len(sys.argv) > 2 else os.path.join(here, "baseline.tex")

    with open(src, newline="", encoding="utf-8") as f:
        rows = [r for r in csv.DictReader(f) if r.get("method")]
    if not rows:
        raise SystemExit(f"{src}: no usable row")

    # ------------------------------------------------------------------ table
    body = []
    for r in rows:
        c = [esc(r["method"]), cell(r["model_type"]), cell(r["post_proc"])]
        for n in SIZES:
            c += [cell(r[f"n{n}_obj"]), cell(r[f"n{n}_gap_pct"]), cell(r[f"n{n}_time"])]
        body.append("  " + " & ".join(c) + r" \\")

    # separators between method families
    out, prev = [], None
    for line, r in zip(body, rows):
        if prev is not None and r["model_type"] != prev:
            out.append(r"  \addlinespace")
        out.append(line)
        prev = r["model_type"]
    table_body = "\n".join(out)

    # ------------------------------------------------------------------ plots
    plots = {}
    for n in SIZES:
        per_type = {}
        for r in rows:
            obj, th = r[f"n{n}_obj"], r[f"n{n}_time_h"]
            if not obj or not th:
                continue
            gap = r[f"n{n}_gap_pct"] or "0"      # HGS = reference, zero gap
            per_type.setdefault(r["model_type"], []).append((float(th), float(gap)))
        plots[n] = per_type

    figs = []
    for i, n in enumerate(SIZES):
        series = []
        for t, (style, _) in TYPE_STYLE.items():
            pts = sorted(plots[n].get(t, []))
            if not pts:
                continue
            coords = " ".join(f"({x:g},{y:g})" for x, y in pts)
            series.append(f"      \\addplot+[only marks,{style}] coordinates {{{coords}}};")
        figs.append(
            f"    \\nextgroupplot[title={{$N={n}$}}]\n" + "\n".join(series))
    groupplots = "\n".join(figs)
    legend = ",".join(lbl for _, lbl in TYPE_STYLE.values())

    tex = TEMPLATE.format(source=os.path.basename(src), table_body=table_body,
                          groupplots=groupplots, legend=legend,
                          nrows=len(rows))
    with open(dst, "w", encoding="utf-8") as f:
        f.write(tex)
    print(f"{dst} written ({len(rows)} methods)")


TEMPLATE = r"""% ---------------------------------------------------------------------------
% Automatically generated by make_tex.py from {source} — do not edit.
% Build:  pdflatex baseline.tex
% ---------------------------------------------------------------------------
\documentclass[11pt,a4paper]{{article}}
\usepackage[margin=2cm,landscape]{{geometry}}
\usepackage[T1]{{fontenc}}
\usepackage{{booktabs}}
\usepackage{{amssymb}}
\usepackage[dvipsnames]{{xcolor}}
\usepackage{{pgfplots}}
\pgfplotsset{{compat=1.18}}
\usepgfplotslibrary{{groupplots}}

\begin{{document}}
\pagestyle{{empty}}

\section*{{CVRP — published baselines}}

Test sets from Ma, Cao \& Chee, \emph{{Learning to Search Feasible and
Infeasible Regions of Routing Problems with Flexible Neural k-Opt}},
NeurIPS 2023 (arXiv:2310.18264), tables 1 and 12.
Gaps are relative to HGS, which serves as the reference.
Times are the published ones, for the complete set.

\bigskip

\begin{{center}}
\small
\begin{{tabular}}{{lll rrr rrr rrr}}
\toprule
& & & \multicolumn{{3}}{{c}}{{$N=20$}} & \multicolumn{{3}}{{c}}{{$N=50$}} & \multicolumn{{3}}{{c}}{{$N=100$}} \\
\cmidrule(lr){{4-6}} \cmidrule(lr){{7-9}} \cmidrule(lr){{10-12}}
Method & Type & Post & Obj. & Gap (\%) & Time & Obj. & Gap (\%) & Time & Obj. & Gap (\%) & Time \\
\midrule
{table_body}
\bottomrule
\end{{tabular}}
\end{{center}}

\bigskip

\begin{{center}}
\begin{{tikzpicture}}
  \begin{{groupplot}}[
      group style={{group size=3 by 1, horizontal sep=1.5cm}},
      width=6.2cm, height=6cm,
      xmode=log, xlabel={{time (h, log scale)}},
      ylabel={{gap to HGS (\%)}},
      grid=both, grid style={{gray!20}},
      every axis title/.style={{above,yshift=2pt}},
      /tikz/mark size=2.6pt,
    ]
{groupplots}
  \end{{groupplot}}
\end{{tikzpicture}}

\medskip
\footnotesize
\textcolor{{black}}{{$\blacksquare$}}~Classical (H) \quad
\textcolor{{RoyalBlue}}{{$\bullet$}}~Learn-to-search \quad
\textcolor{{BrickRed}}{{$\blacktriangle$}}~Learn-to-construct
\end{{center}}

\vfill
\footnotesize
{nrows} methods. Bottom-left = better (fast and close to HGS).
HGS sits at zero gap by construction; its cost is its computation time.

\end{{document}}
"""


if __name__ == "__main__":
    main()
